version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: manojkumar0143/bookztron-backend:latest
    container_name: bookztron-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/bookztron
    depends_on:
      - mongo

  frontend:
    image: manojkumar0143/bookztron-frontend:latest
    container_name: bookztron-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
